### ISSUE TITLE
Alternative authentication methods

### ISSUE THREAD

**Issue by egalpin** [transceptor-technology/aiogcd#1]
Thanks for this project, excited to have found it!

Is there a way to use service accounts (with JSON key) to authorize requests with this lib?  Happy to work on adding this functionality if there is a known path!

**Comment by joente** [comment]
Thank you for liking the project!

The library only supports token authentication. That said, I guess that if you know how to use service account authentication using the Google API, then implementing that kind of authentication to this library should not be too hard.

Token authentication is done by [token.py](https://github.com/transceptor-technology/aiogcd/blob/master/aiogcd/connector/token.py) which is used by the  [connector.py](https://github.com/transceptor-technology/aiogcd/blob/master/aiogcd/connector/connector.py). It would be nice to see a pull request!

**Comment by egalpin** [comment]
Looks like this is a good starting place:  https://developers.google.com/identity/protocols/OAuth2ServiceAccount

I'll see what I can work out :-)

**Comment by nikita-davydov** [comment]
How can we use it in app engine? App Engine has its service account by default and I can't figure out what type of token I should use there

**Comment by joente** [comment]
> How can we use it in app engine? App Engine has its service account by default and I can't figure out what type of token I should use there

This library is created to use the google datastore *without* App engine. That said, it is probably still possible (but I did not test this) to use it with app engine by using the `GcdServiceAccountConnector` and provide it with a service file. A service file can be created from [here](https://console.cloud.google.com/iam-admin/serviceaccounts) and should look something like this: 

```json
{
      "type": "service_account",
      "project_id": "my-project-id",
      "private_key_id": "...",
      "private_key": "-----BEGIN PRIVATE KEY----- XXXXXXXXX\n-----END PRIVATE KEY-----\n",
      "client_email": "...",
      "client_id": "...",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "...",
      "client_x509_cert_url": "..."
}
```

Thus,
```python
from aiogcd.connector import GcdServiceAccountConnector
...
gcd = GcdServiceAccountConnector(
        project_id='my-project-id',
        service_file='path-to-service-file')
```
