### ISSUE TITLE
Infinite loop while obtaining ServiceAccount token

### ISSUE THREAD

**Issue by doubtx** [transceptor-technology/aiogcd#11]
service_account_token.py

        async with ensure_session(self.session) as s:
            response = await s.post(
                url,
                data=payload,
                headers=headers,
                timeout=60
            )

        return await response.json()

causes infinite loop in some requests, changing to: 

         async with ensure_session(self.session) as s:
            response = await s.post(
                url,
                data=payload,
                headers=headers,
                timeout=60
            )

		json = await response.json()
			
        return json

helps

**Comment by joente** [comment]
Thx! Can you create a pull request?

**Comment by joente** [comment]
see pr: #12
