### ISSUE TITLE
yield inside async function error

### ISSUE THREAD

**Issue by joente** [transceptor-technology/aiogcd#9]
Pull request #8 introduced a `yield inside async function` error.

**Comment by egalpin** [comment]
What version of python are you using?

**Comment by joente** [comment]
This happens with Python 3.5.x. I think the `yield` can be replace with `return` to make it work in Python 3.5 and higher?

**Comment by egalpin** [comment]
Ah, not 100% sure on that; you may be right.  The [async_contextmanager](http://pythonhosted.org/asyncio_extras/#module-asyncio_extras.contextmanager) docs mentioned the use of `yield_` instead for 3.5, but I'm not sure that that's 3.6 compatible

**Comment by joente** [comment]
I think you mean `await yield_`. Looks like that works in both 3.5 and 3.6.

**Comment by egalpin** [comment]
Ah, yes that's what I meant.  Perfect :-)
